spring:
  application:
    title: "Twitter API"
    version: ${APP_VERSION:"x.x.x"}
    url: ${SERVER_URL:http://localhost:8080/}

  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: test
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
  h2:
    console:
      enabled: true
  flyway:
    enabled: false
  cache:
    type: NONE

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

api:
  security:
    token:
      secret: "secret"
      issuer: "issuer"
      expiration-seconds: 3600