CREATE TABLE tweet_view (
    tweet_id UUID NOT NULL REFERENCES tweet(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (tweet_id, user_id)
);
